"""initial_schema

Revision ID: 1926b71611fb
Revises: 
Create Date: 2026-09-21 21:49:31.401496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1926b71611fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_telemetry_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('model_requested', sa.String(length=64), nullable=False),
    sa.Column('model_resolved', sa.String(length=64), nullable=False),
    sa.Column('input_chars', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('is_truncated', sa.Boolean(), nullable=False),
    sa.Column('repair_successful', sa.Boolean(), nullable=False),
    sa.Column('cards_generated', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_telemetry_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_telemetry_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_telemetry_logs_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_telemetry_logs_user_id'), ['user_id'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_user_id'), ['user_id'], unique=False)

    op.create_table('daily_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('total_reviewed', sa.Integer(), nullable=True),
    sa.Column('new_cards_learned', sa.Integer(), nullable=True),
    sa.Column('session_duration', sa.Integer(), nullable=True),
    sa.Column('true_retention', sa.Float(), nullable=True),
    sa.Column('mental_effort', sa.Integer(), nullable=False),
    sa.Column('association_utility', sa.Integer(), nullable=False),
    sa.Column('perceived_retention', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('generation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('granularity_mode', sa.String(), nullable=True),
    sa.Column('density', sa.String(), nullable=True),
    sa.Column('volume', sa.String(), nullable=True),
    sa.Column('custom_instruction', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('cards_count', sa.Integer(), nullable=True),
    sa.Column('result_cards_json', sa.String(), nullable=True),
    sa.Column('is_deferred', sa.Boolean(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('json_repair_applied', sa.Boolean(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_trace', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('invite_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('used_by_user_id', sa.String(length=64), nullable=True),
    sa.Column('used_by_username', sa.String(length=64), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invite_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_codes_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_invite_codes_id'), ['id'], unique=False)

    op.create_table('phrases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phrases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phrases_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_phrases_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_phrases_user_id'), ['user_id'], unique=False)

    op.create_table('practice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('gold_standard', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_items_item_id'), ['item_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_practice_items_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_items_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_practice_items_user_subject', ['user_id', 'subject'], unique=False)

    op.create_table('practice_session_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_session_logs', schema=None) as batch_op:
        batch_op.create_index('ix_practice_logs_user_subject', ['user_id', 'subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_session_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_session_logs_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_session_logs_user_id'), ['user_id'], unique=False)

    op.create_table('topic_knowledge_graphs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('graph_data', sa.JSON(), nullable=False),
    sa.Column('tree_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'subject', name='uq_topic_knowledge_graphs_user_subject')
    )
    with op.batch_alter_table('topic_knowledge_graphs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_knowledge_graphs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_knowledge_graphs_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_knowledge_graphs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_topic_knowledge_graphs_user_subject', ['user_id', 'subject'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('is_resting', sa.Boolean(), nullable=True),
    sa.Column('rest_ends_at', sa.DateTime(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.Column('last_morning_sent', sa.String(), nullable=True),
    sa.Column('last_evening_sent', sa.String(), nullable=True),
    sa.Column('last_due_notified_at', sa.DateTime(), nullable=True),
    sa.Column('last_due_count', sa.Integer(), nullable=True),
    sa.Column('is_experiment_participant', sa.Boolean(), nullable=False),
    sa.Column('experiment_phase', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_telegram_id'), ['telegram_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('target_retention', sa.Float(), nullable=True),
    sa.Column('assoc_preference', sa.String(), nullable=True),
    sa.Column('subject_limits', sa.JSON(), nullable=True),
    sa.Column('is_experiment_participant', sa.Boolean(), nullable=False),
    sa.Column('experiment_phase', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_settings_user_id'), ['user_id'], unique=True)

    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('secondary_text', sa.String(), nullable=True),
    sa.Column('translation', sa.String(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('last_review', sa.DateTime(), nullable=True),
    sa.Column('next_review', sa.DateTime(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=True),
    sa.Column('is_anchored', sa.Boolean(), nullable=True),
    sa.Column('mnemonic', sa.JSON(), nullable=True),
    sa.Column('has_seen_intro', sa.Boolean(), nullable=True),
    sa.Column('intro_phase', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('example', sa.String(), nullable=True),
    sa.Column('topological_rank', sa.Integer(), nullable=True),
    sa.Column('organ_slug', sa.String(), nullable=True),
    sa.Column('layer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['phrase_id'], ['phrases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_index('idx_card_user_next_review', ['user_id', 'next_review'], unique=False)
        batch_op.create_index('idx_card_user_subject', ['user_id', 'subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_next_review'), ['next_review'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_organ_slug'), ['organ_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_topological_rank'), ['topological_rank'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_user_id'), ['user_id'], unique=False)

    op.create_table('review_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_time', sa.DateTime(), nullable=False),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('elapsed_days', sa.Integer(), nullable=True),
    sa.Column('scheduled_days', sa.Integer(), nullable=True),
    sa.Column('has_association', sa.Boolean(), nullable=True),
    sa.Column('response_time', sa.Integer(), nullable=True),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_outlier', sa.Boolean(), nullable=False),
    sa.Column('is_cram', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_review_logs_id'))

    op.drop_table('review_logs')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cards_user_id'))
        batch_op.drop_index(batch_op.f('ix_cards_topological_rank'))
        batch_op.drop_index(batch_op.f('ix_cards_subject'))
        batch_op.drop_index(batch_op.f('ix_cards_organ_slug'))
        batch_op.drop_index(batch_op.f('ix_cards_next_review'))
        batch_op.drop_index(batch_op.f('ix_cards_id'))
        batch_op.drop_index('idx_card_user_subject')
        batch_op.drop_index('idx_card_user_next_review')

    op.drop_table('cards')
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_settings_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_settings_id'))

    op.drop_table('user_settings')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_id'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('topic_knowledge_graphs', schema=None) as batch_op:
        batch_op.drop_index('ix_topic_knowledge_graphs_user_subject')
        batch_op.drop_index(batch_op.f('ix_topic_knowledge_graphs_user_id'))
        batch_op.drop_index(batch_op.f('ix_topic_knowledge_graphs_subject'))
        batch_op.drop_index(batch_op.f('ix_topic_knowledge_graphs_id'))

    op.drop_table('topic_knowledge_graphs')
    with op.batch_alter_table('practice_session_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_session_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_practice_session_logs_subject'))
        batch_op.drop_index(batch_op.f('ix_practice_session_logs_id'))
        batch_op.drop_index('ix_practice_logs_user_subject')

    op.drop_table('practice_session_logs')
    with op.batch_alter_table('practice_items', schema=None) as batch_op:
        batch_op.drop_index('ix_practice_items_user_subject')
        batch_op.drop_index(batch_op.f('ix_practice_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_practice_items_subject'))
        batch_op.drop_index(batch_op.f('ix_practice_items_item_id'))
        batch_op.drop_index(batch_op.f('ix_practice_items_id'))

    op.drop_table('practice_items')
    with op.batch_alter_table('phrases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phrases_user_id'))
        batch_op.drop_index(batch_op.f('ix_phrases_subject'))
        batch_op.drop_index(batch_op.f('ix_phrases_id'))

    op.drop_table('phrases')
    with op.batch_alter_table('invite_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_codes_id'))
        batch_op.drop_index(batch_op.f('ix_invite_codes_code'))

    op.drop_table('invite_codes')
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_generation_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_generation_jobs_id'))

    op.drop_table('generation_jobs')
    with op.batch_alter_table('daily_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_sessions_id'))

    op.drop_table('daily_sessions')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_user_id'))
        batch_op.drop_index(batch_op.f('ix_categories_id'))

    op.drop_table('categories')
    with op.batch_alter_table('ai_telemetry_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_telemetry_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_telemetry_logs_job_id'))
        batch_op.drop_index(batch_op.f('ix_ai_telemetry_logs_id'))

    op.drop_table('ai_telemetry_logs')
    # ### end Alembic commands ###
